T = terraform

all: init validate plan apply

init:
	$(T) init

validate:
	$(T) validate

plan:
	$(T) plan

apply:
	$(T) apply -auto-approve

destroy:
	$(T) state rm yandex_iam_service_account.sa
	$(T) state rm yandex_iam_service_account_static_access_key.sa-static-key
	$(T) state rm yandex_resourcemanager_folder_iam_member.sa_roles
	$(T) state rm yandex_storage_bucket.data_bucket
	$(T) destroy -auto-approve

clean:
	rm -rf .terraform/
	rm  .terraform.lock.hcl
	rm terraform.tfstate
	rm terraform.tfstate.backup
	rm *.tfstate.*
